version: '2'

services:
  
  proxy:
    
    build: ./proxy/
    
    ports:
      - 23:23 

    depends_on:
      - server
    
    external_links: 
      - server
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./log_directory:/proxy/log_directory
      - ./IP_PORT:/proxy/IP_PORT
      - ./UNAME_PASS:/proxy/UNAME_PASS

  server:
    build: ./echo_server/
